### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [chadillac/mdns_recon#1]
You plan on adding that you found it with ArchAssault, or are you gonna leave the distro that you use out of the mix?

**Comment by chadillac** [comment]
Gonna add it, currently being suppressed by Akamai legal, pending review
yadda yadda yadda, don't get me started. I'm thoroughly disgusted with them
and their hijacking of my independent research at the moment.

**Comment by archey** [comment]
Understood, I would appreciate a shoutout at least. Itd be nice while all the press is out.
